% script for writing the html documentation of the matlab toolbox
cd /Users/morsdorf/matlab/mytoolbox/alstools/

dirstr = {   'baseproducts', ...
             'geocord', ...
             'geocord/geodetic', ...
             'datafun', ...
             'datafun/convers', ...
             'datafun/fileio', ...
             'datafun/utils', ...
             'products_bsc', ...
             'products_vgt', ...
             'products_vgt/pixvoxbased', ...
             'products_vgt/singletree', ...
             'products_vgt/singletree/utils', ...
             'misc', ...
             'scripts', ...
             'simulation', ...
             'simulation/simwave', ...
             'visualization/2dgraphs', ...
             'visualization/3dgraphs', ...
             'visualization/animations', ...
             'visualization/utils'};
                 
m2html('mfiles',dirstr,'htmldir','doc', ...
       'template','frame','index','menu','graph','on', ...
       'search','off','globalHypertextLinks','on');