function [] = dtm2erm(dtm,filename);
% function [] = dtm2erm(dtm,filename);
% writes a dtm to a ermmapper file

% Felix Morsdorf, RSL Zurich, Sep. 2006  
% write  header information
 
  k = findstr('.',filename)-1;
  
  if ~isempty(k)
    outfilename = [filename(1:k)];
  else
    outfilename = filename;
    filename = [filename,'.ers'];
  end
  
  str = construct_hdr(dtm.x,dtm.y,filename);
  fid = fopen([outfilename,'.ers'],'w');
  for i = 1:length(str)
    fprintf(fid,'%s\n',str{i});
  end
  fclose(fid);
  
  % write binary data file
  dtm.z(isnan(dtm.z)) = 0;
  %dtm.z = flipud(dtm.z)';
  dtm.z = dtm.z';
  [fid,message] = fopen(outfilename,'w','b');
  fwrite(fid,dtm.z(:),'single');
  fclose(fid);
  

%-------------------------------------------------------------------------------
function [str] = construct_hdr(x,y,fname);
  % construct header  ers header fields :
  [s,DATE] = unix('date');
  xd = median(abs(diff(x)));
  yd = median(abs(diff(y)));
  str = {'DatasetHeader Begin', ...
  '	Version		= "5.5"', ...
 ['	LastUpdated	= ',DATE(1:end-1)], ...
  '	DataSetType	= ERStorage', ...
  '	DataType	= Raster', ...
  '	ByteOrder	= MSBFirst', ...
  '	CoordinateSpace Begin', ...
  '		Datum		= "BERNNEW"', ...
  '		Projection	= "SWISSNEW"', ...
  '		CoordinateType	= EN', ...
  '		Rotation	= 0:0:0.0', ...
  '	CoordinateSpace End', ...
  '	RasterInfo Begin', ...
  '		CellType	= IEEE4ByteReal', ...
  '		NullCellValue	= 0', ...
 ['		NrOfLines	= ',num2str(length(y))], ...
 ['		NrOfCellsPerLine	= ',num2str(length(x))], ...
  '		CellInfo Begin', ...
 ['			Xdimension = ',num2str(xd)], ...
 ['			Ydimension = ',num2str(yd)], ...
  '		CellInfo End', ...
  '		RegistrationCoord Begin', ...
  ['			Eastings	= ',num2str(minnan(x)-(xd/2))], ...
  ['			Northings	= ',num2str(maxnan(y)+(yd/2))], ...
  '		RegistrationCoord End', ...
  '		NrOfBands	= 1', ...
  '		BandId Begin', ...
  '			Value		= "Pseudo Layer"', ...
  '		BandId End', ...
  '		RegionInfo Begin', ...
  '			Type		= Polygon', ...
  '			RegionName	= "All"', ...
  ['			SourceDataset	= "',fname,'"'], ...
  '			SubRegion	= {', ...
  '				0	0', ...
  ['				0	',num2str(length(y))], ...
  ['				',num2str(length(x)),'  ',num2str(length(y))], ...
  ['				',num2str(length(x)),'	0'], ...
  '			}', ...
  '		RegionInfo End', ...
  '	RasterInfo End', ...
  'DatasetHeader End'};

  


